---
scm_provider: "github"
control_scm_org: "aap-casc-platform-demo"
control_repo: "casc-platform-control"
control_branch: "main"
platform_scm_org: "aap-casc-platform-demo"
platform_repo: "casc-platform-global"
create_missing_env_branches: true

job_templates:
  genesis: "jt-platform-genesis"
  bootstrap: "jt-platform-bootstrap_tenant"
  dispatcher: "jt-platform-casc_dispatcher"
  drift_detection: "jt-platform-drift_detection"

env_branch_map:
  poc: dev
  prod: main
